src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function getId()
    {
        return $this->id;
    }

    //геттеры и сеттеры

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description): void
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param mixed $created_at
     */
    public function setCreatedAt($created_at): void
    {
        $this->created_at = $created_at;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                    'label' => 'label.article.name',
                    'attr' => [
                        'placeholder' => 'Enter name here...',
                    ],
                ]
            )
            ->add('created_at', DateType::class, [
                    'label' => 'label.article.created_at',
                ]
            )
            ->add('description', TextType::class, [
                    'label' => 'label.article.description',
                    'attr' => [
                        'placeholder' => 'Enter description here...',
                    ],
                ]
            )
            ->add('submit', SubmitType::class, [
                    'label' => 'submit',
                ]
            )
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

templates/article/qrcode.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <img src="{{ asset('qr/qrcode.png') }}" />
{% endblock %}

templates/article/read.html.twig
{% extends 'base.html.twig' %}
    {% block title %}Article{% endblock %}
{% block body %}
    {% for article in articles %}
        <tr>
            <td><a href="{{ path('article_read', {'id': article.id}) }}">{{ article.name }}</a></td>
            <td>{{ article.description }}</td>
            <td>{{ article.createdAt|date('Y-m-d H:i:s') }}</td>
            <td><a href="{{ path('article_update', {'id': article.id}) }}">Изменить</a></td>
            <td><a href="{{ path('article_delete', {'id': article.id}) }}">Удалить</a></td>
        </tr>
        <br>
    {% endfor %}
    <a href="{{ path('article_create') }}">Создать</a>
{% endblock %}

templates/article/update.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form(form) }}
{% endblock %}